// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.
// Code generated by buildx tool. DO NOT EDIT.

package bootstrap

import (
	apiPublicRepository "gen_gin_tpl/internal/infrastructure/persistence"
	apiPublicService "gen_gin_tpl/internal/application/public"
	apiPublicHandler "gen_gin_tpl/internal/interfaces/api"

	webViewsRepository "gen_gin_tpl/internal/infrastructure/persistence"
	webViewsService "gen_gin_tpl/internal/application/views"
	webViewsHandler "gen_gin_tpl/internal/interfaces/web"

	"gen_gin_tpl/internal/infrastructure/query"
	"gorm.io/gorm"
)

type appContext struct {
	ApiPublicHandler *apiPublicHandler.PublicHandler
	WebViewsHandler *webViewsHandler.ViewsHandler
}

func NewAppContext(db *gorm.DB) *appContext {
	apiPublicRepo := &apiPublicRepository.ApiPublicRepository{DB: db, Q: query.Q}
	apiPublicService := &apiPublicService.ApiPublicService{Repo: apiPublicRepo}
	apiPublicHandler := &apiPublicHandler.PublicHandler{Service: apiPublicService}

	webViewsRepo := &webViewsRepository.WebViewsRepository{DB: db, Q: query.Q}
	webViewsService := &webViewsService.WebViewsService{Repo: webViewsRepo}
	webViewsHandler := &webViewsHandler.ViewsHandler{Service: webViewsService}

	return &appContext{
		ApiPublicHandler: apiPublicHandler,
		WebViewsHandler: webViewsHandler,
	}
}