// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"toolbox/internal/models"
)

func newFileRecord(db *gorm.DB, opts ...gen.DOOption) fileRecord {
	_fileRecord := fileRecord{}

	_fileRecord.fileRecordDo.UseDB(db, opts...)
	_fileRecord.fileRecordDo.UseModel(&models.FileRecord{})

	tableName := _fileRecord.fileRecordDo.TableName()
	_fileRecord.ALL = field.NewAsterisk(tableName)
	_fileRecord.ID = field.NewInt64(tableName, "id")
	_fileRecord.Url = field.NewString(tableName, "url")
	_fileRecord.Name = field.NewString(tableName, "name")
	_fileRecord.Type = field.NewString(tableName, "type")
	_fileRecord.Size = field.NewInt64(tableName, "size")
	_fileRecord.Hash = field.NewString(tableName, "hash")
	_fileRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_fileRecord.fillFieldMap()

	return _fileRecord
}

type fileRecord struct {
	fileRecordDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Url       field.String // 文件Url
	Name      field.String // 文件名
	Type      field.String // 文件类型
	Size      field.Int64  // 文件大小
	Hash      field.String // 文件哈希
	CreatedAt field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (f fileRecord) Table(newTableName string) *fileRecord {
	f.fileRecordDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fileRecord) As(alias string) *fileRecord {
	f.fileRecordDo.DO = *(f.fileRecordDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fileRecord) updateTableName(table string) *fileRecord {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.Url = field.NewString(table, "url")
	f.Name = field.NewString(table, "name")
	f.Type = field.NewString(table, "type")
	f.Size = field.NewInt64(table, "size")
	f.Hash = field.NewString(table, "hash")
	f.CreatedAt = field.NewTime(table, "created_at")

	f.fillFieldMap()

	return f
}

func (f *fileRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fileRecord) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 7)
	f.fieldMap["id"] = f.ID
	f.fieldMap["url"] = f.Url
	f.fieldMap["name"] = f.Name
	f.fieldMap["type"] = f.Type
	f.fieldMap["size"] = f.Size
	f.fieldMap["hash"] = f.Hash
	f.fieldMap["created_at"] = f.CreatedAt
}

func (f fileRecord) clone(db *gorm.DB) fileRecord {
	f.fileRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fileRecord) replaceDB(db *gorm.DB) fileRecord {
	f.fileRecordDo.ReplaceDB(db)
	return f
}

type fileRecordDo struct{ gen.DO }

func (f fileRecordDo) Debug() *fileRecordDo {
	return f.withDO(f.DO.Debug())
}

func (f fileRecordDo) WithContext(ctx context.Context) *fileRecordDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileRecordDo) ReadDB() *fileRecordDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileRecordDo) WriteDB() *fileRecordDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileRecordDo) Session(config *gorm.Session) *fileRecordDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileRecordDo) Clauses(conds ...clause.Expression) *fileRecordDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileRecordDo) Returning(value interface{}, columns ...string) *fileRecordDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileRecordDo) Not(conds ...gen.Condition) *fileRecordDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileRecordDo) Or(conds ...gen.Condition) *fileRecordDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileRecordDo) Select(conds ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileRecordDo) Where(conds ...gen.Condition) *fileRecordDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileRecordDo) Order(conds ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileRecordDo) Distinct(cols ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileRecordDo) Omit(cols ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileRecordDo) Join(table schema.Tabler, on ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileRecordDo) Group(cols ...field.Expr) *fileRecordDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileRecordDo) Having(conds ...gen.Condition) *fileRecordDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileRecordDo) Limit(limit int) *fileRecordDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileRecordDo) Offset(offset int) *fileRecordDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fileRecordDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileRecordDo) Unscoped() *fileRecordDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileRecordDo) Create(values ...*models.FileRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileRecordDo) CreateInBatches(values []*models.FileRecord, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileRecordDo) Save(values ...*models.FileRecord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileRecordDo) First() (*models.FileRecord, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileRecord), nil
	}
}

func (f fileRecordDo) Take() (*models.FileRecord, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileRecord), nil
	}
}

func (f fileRecordDo) Last() (*models.FileRecord, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileRecord), nil
	}
}

func (f fileRecordDo) Find() ([]*models.FileRecord, error) {
	result, err := f.DO.Find()
	return result.([]*models.FileRecord), err
}

func (f fileRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.FileRecord, err error) {
	buf := make([]*models.FileRecord, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileRecordDo) FindInBatches(result *[]*models.FileRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileRecordDo) Attrs(attrs ...field.AssignExpr) *fileRecordDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileRecordDo) Assign(attrs ...field.AssignExpr) *fileRecordDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileRecordDo) Joins(fields ...field.RelationField) *fileRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileRecordDo) Preload(fields ...field.RelationField) *fileRecordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileRecordDo) FirstOrInit() (*models.FileRecord, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileRecord), nil
	}
}

func (f fileRecordDo) FirstOrCreate() (*models.FileRecord, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.FileRecord), nil
	}
}

func (f fileRecordDo) FindByPage(offset int, limit int) (result []*models.FileRecord, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileRecordDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileRecordDo) Delete(models ...*models.FileRecord) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileRecordDo) withDO(do gen.Dao) *fileRecordDo {
	f.DO = *do.(*gen.DO)
	return f
}
