// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q          = new(Query)
	Article    *article
	Category   *category
	DNSTable   *dNSTable
	FileRecord *fileRecord
	Home       *home
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Article = &Q.Article
	Category = &Q.Category
	DNSTable = &Q.DNSTable
	FileRecord = &Q.FileRecord
	Home = &Q.Home
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:         db,
		Article:    newArticle(db, opts...),
		Category:   newCategory(db, opts...),
		DNSTable:   newDNSTable(db, opts...),
		FileRecord: newFileRecord(db, opts...),
		Home:       newHome(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Article    article
	Category   category
	DNSTable   dNSTable
	FileRecord fileRecord
	Home       home
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Article:    q.Article.clone(db),
		Category:   q.Category.clone(db),
		DNSTable:   q.DNSTable.clone(db),
		FileRecord: q.FileRecord.clone(db),
		Home:       q.Home.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:         db,
		Article:    q.Article.replaceDB(db),
		Category:   q.Category.replaceDB(db),
		DNSTable:   q.DNSTable.replaceDB(db),
		FileRecord: q.FileRecord.replaceDB(db),
		Home:       q.Home.replaceDB(db),
	}
}

type queryCtx struct {
	Article    *articleDo
	Category   *categoryDo
	DNSTable   *dNSTableDo
	FileRecord *fileRecordDo
	Home       *homeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Article:    q.Article.WithContext(ctx),
		Category:   q.Category.WithContext(ctx),
		DNSTable:   q.DNSTable.WithContext(ctx),
		FileRecord: q.FileRecord.WithContext(ctx),
		Home:       q.Home.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
