// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"toolbox/internal/models"
)

func newHome(db *gorm.DB, opts ...gen.DOOption) home {
	_home := home{}

	_home.homeDo.UseDB(db, opts...)
	_home.homeDo.UseModel(&models.Home{})

	tableName := _home.homeDo.TableName()
	_home.ALL = field.NewAsterisk(tableName)
	_home.ID = field.NewInt64(tableName, "id")
	_home.Icon = field.NewString(tableName, "icon")
	_home.Name = field.NewString(tableName, "name")
	_home.Path = field.NewString(tableName, "path")
	_home.Sort = field.NewInt(tableName, "sort")
	_home.IconType = field.NewInt(tableName, "icon_type")
	_home.Position = field.NewInt(tableName, "position")
	_home.CreatedAt = field.NewTime(tableName, "created_at")
	_home.UpdatedAt = field.NewTime(tableName, "updated_at")

	_home.fillFieldMap()

	return _home
}

type home struct {
	homeDo

	ALL       field.Asterisk
	ID        field.Int64  // ID
	Icon      field.String // 图标
	Name      field.String // 名称
	Path      field.String // 路径
	Sort      field.Int    // 排序值，值越大越靠前，默认0
	IconType  field.Int    // 图标类型
	Position  field.Int    // 位置类型
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (h home) Table(newTableName string) *home {
	h.homeDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h home) As(alias string) *home {
	h.homeDo.DO = *(h.homeDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *home) updateTableName(table string) *home {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewInt64(table, "id")
	h.Icon = field.NewString(table, "icon")
	h.Name = field.NewString(table, "name")
	h.Path = field.NewString(table, "path")
	h.Sort = field.NewInt(table, "sort")
	h.IconType = field.NewInt(table, "icon_type")
	h.Position = field.NewInt(table, "position")
	h.CreatedAt = field.NewTime(table, "created_at")
	h.UpdatedAt = field.NewTime(table, "updated_at")

	h.fillFieldMap()

	return h
}

func (h *home) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *home) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 9)
	h.fieldMap["id"] = h.ID
	h.fieldMap["icon"] = h.Icon
	h.fieldMap["name"] = h.Name
	h.fieldMap["path"] = h.Path
	h.fieldMap["sort"] = h.Sort
	h.fieldMap["icon_type"] = h.IconType
	h.fieldMap["position"] = h.Position
	h.fieldMap["created_at"] = h.CreatedAt
	h.fieldMap["updated_at"] = h.UpdatedAt
}

func (h home) clone(db *gorm.DB) home {
	h.homeDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h home) replaceDB(db *gorm.DB) home {
	h.homeDo.ReplaceDB(db)
	return h
}

type homeDo struct{ gen.DO }

func (h homeDo) Debug() *homeDo {
	return h.withDO(h.DO.Debug())
}

func (h homeDo) WithContext(ctx context.Context) *homeDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h homeDo) ReadDB() *homeDo {
	return h.Clauses(dbresolver.Read)
}

func (h homeDo) WriteDB() *homeDo {
	return h.Clauses(dbresolver.Write)
}

func (h homeDo) Session(config *gorm.Session) *homeDo {
	return h.withDO(h.DO.Session(config))
}

func (h homeDo) Clauses(conds ...clause.Expression) *homeDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h homeDo) Returning(value interface{}, columns ...string) *homeDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h homeDo) Not(conds ...gen.Condition) *homeDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h homeDo) Or(conds ...gen.Condition) *homeDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h homeDo) Select(conds ...field.Expr) *homeDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h homeDo) Where(conds ...gen.Condition) *homeDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h homeDo) Order(conds ...field.Expr) *homeDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h homeDo) Distinct(cols ...field.Expr) *homeDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h homeDo) Omit(cols ...field.Expr) *homeDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h homeDo) Join(table schema.Tabler, on ...field.Expr) *homeDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h homeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *homeDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h homeDo) RightJoin(table schema.Tabler, on ...field.Expr) *homeDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h homeDo) Group(cols ...field.Expr) *homeDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h homeDo) Having(conds ...gen.Condition) *homeDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h homeDo) Limit(limit int) *homeDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h homeDo) Offset(offset int) *homeDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h homeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *homeDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h homeDo) Unscoped() *homeDo {
	return h.withDO(h.DO.Unscoped())
}

func (h homeDo) Create(values ...*models.Home) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h homeDo) CreateInBatches(values []*models.Home, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h homeDo) Save(values ...*models.Home) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h homeDo) First() (*models.Home, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Home), nil
	}
}

func (h homeDo) Take() (*models.Home, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Home), nil
	}
}

func (h homeDo) Last() (*models.Home, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Home), nil
	}
}

func (h homeDo) Find() ([]*models.Home, error) {
	result, err := h.DO.Find()
	return result.([]*models.Home), err
}

func (h homeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Home, err error) {
	buf := make([]*models.Home, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h homeDo) FindInBatches(result *[]*models.Home, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h homeDo) Attrs(attrs ...field.AssignExpr) *homeDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h homeDo) Assign(attrs ...field.AssignExpr) *homeDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h homeDo) Joins(fields ...field.RelationField) *homeDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h homeDo) Preload(fields ...field.RelationField) *homeDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h homeDo) FirstOrInit() (*models.Home, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Home), nil
	}
}

func (h homeDo) FirstOrCreate() (*models.Home, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Home), nil
	}
}

func (h homeDo) FindByPage(offset int, limit int) (result []*models.Home, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h homeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h homeDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h homeDo) Delete(models ...*models.Home) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *homeDo) withDO(do gen.Dao) *homeDo {
	h.DO = *do.(*gen.DO)
	return h
}
